package controls.ai;

import java.util.LinkedList;

/**
 * The Path class is used by Player to navigate from some start to an end.
 * These paths are generated by World.
 * @author Matt Crow
 */
public class Path {
    private final LinkedList<PathInfo> path;
    public Path(){
        path = new LinkedList<>();
    }
    
    public boolean noneLeft(){
        return path.isEmpty();
    }
    
    /**
     * Gets the first element in the path
     * @return 
     */
    public PathInfo get(){
        return path.getFirst();
    }
    
    public void push(PathInfo p){
        path.push(p);
    }
    
    public void deque(){
        path.removeFirst();
    }
}
