/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Client;

public class App {
    
    public static void main(String[] args) {
        start.MainWindow.main(args);
    }
}
