/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Server;
import world.build.Build;
import util.Settings;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        for(Build b : Settings.getDataSet().getAllBuilds()){
            System.out.println(b.getDescription());
        }
    }
}
