package world.entities;

import world.World;
import world.build.actives.ElementalActive;

/**
 * The AOEProjectile class is used to represent the area-of-effect explosion
 * generated by some seed projectiles.
 *
 * I may later replace this class with an Explosion class, allowing me to draw a
 * rounded shape without lots of projectiles. However, this has the downside of
 * being difficult to make tiles block the explosion, as it wouldn't be easy to
 * make parts of the explosion block while the rest continues to expand, and I
 * don't think I want explosions going though blocking tiles.
 *
 * @author Matt Crow
 */
public class AOEProjectile extends Projectile {

    public AOEProjectile(World inWorld, int id, int x, int y, int degrees, int momentum, AbstractPlayer attackUser, ElementalActive a) {
        super(inWorld, id, x, y, degrees, momentum, attackUser, a);
        setRange((int) a.getAOE());
    }
}
